version: 2

references:
  node_defaults: &node_defaults
    working_directory: ~/repo
    docker:
      - image: circleci/node:14

jobs:
  checkout_code:
    <<: *node_defaults
    steps:
      - checkout
      - persist_to_workspace:
          root: ~/repo
          paths:
            - .

  bundle:
    <<: *node_defaults
    steps:
      - attach_workspace:
          at: ~/repo
      - restore_cache:
          key: npm-v1-{{ checksum "package-lock.json" }}
      - run: npm install
      - save_cache:
          key: npm-v1-{{ checksum "package-lock.json" }}
          paths:
            - ~/repo/node_modules
      - persist_to_workspace:
          root: ~/repo
          paths:
            - node_modules

  run_test:
    <<: *node_defaults
    parallelism: 4
    steps:
      - attach_workspace:
          at: ~/repo
      - run:
          name: run tests
          command: npm run test


  run_lint:
    <<: *node_defaults
    steps:
      - attach_workspace:
          at: ~/repo
      - run:
          name: Run JS Linter
          command: npm run lint

  run_typecheck:
    <<: *node_defaults
    steps:
      - attach_workspace:
          at: ~/repo
      - run:
          name: Run TypeScript
          command: npm run typecheck

  run_lint_commit_message:
    <<: *node_defaults
    steps:
      - attach_workspace:
          at: ~/repo
      - run:
          name: Define environment variable with lastest commit's message
          command: |
            echo 'export COMMIT_MESSAGE=$(git log -1 --pretty=format:"%s")' >> $BASH_ENV
            source $BASH_ENV
      - run:
          name: Lint commit message
          command: echo "$COMMIT_MESSAGE" | npx commitlint

  release:
    <<: *node_defaults
    steps:
      - attach_workspace:
          at: ~/repo
      - run:
          name: Trust this ssh key
          command: mkdir -p ~/.ssh/ && touch ~/.ssh/known_hosts && ssh-keyscan github.com >> ~/.ssh/known_hosts
      - run:
          name: Semantic release
          command: npm run semantic-release

  build_image:
    working_directory: ~/repo
    docker:
      - image: docker:17.05.0-ce-git
    steps:
      - checkout
      - run:
          name: Get the recent changes
          command: git pull origin master
      - setup_remote_docker
      - run:
          name: Install dependencies
          command: apk add --no-cache jq
      - restore_cache:
          keys:
            - v1-{{ .Branch }}
          paths:
            - /caches/app.tar
      - run:
          name: Load Docker image layer cache
          command: |
            set +o pipefail
            docker load -i /caches/app.tar | true
      - run:
          name: Build application Docker image
          command: |
            docker build --cache-from=app -t app .
      - run:
          name: Save Docker image layer cache
          command: |
            mkdir -p /caches
            docker save -o /caches/app.tar app
      - deploy:
          name: Push application Docker image
          command: |
            docker login ghcr.io -u USERNAME -p${CR_PAT}
            docker tag app "ghcr.io/gridcat/$(jq -r '.name' package.json):$(jq -r '.version' package.json)"
            docker push "ghcr.io/gridcat/$(jq -r '.name' package.json):$(jq -r '.version' package.json)"

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - checkout_code

      - bundle:
          requires:
            - checkout_code

      - run_lint:
          requires:
            - bundle

      - run_typecheck:
          requires:
            - bundle

      - run_test:
          requires:
            - bundle

      - run_lint_commit_message:
          requires:
            - bundle

      - release:
          filters:
            branches:
              only: master
          requires:
            - run_lint_commit_message
            - run_test
            - run_typecheck
            - run_lint
          context: semantic-release
      
      - build_image:
          filters:
            branches:
              only: master
          requires:
            - release
          context: git-container-registry
